apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-dev
  template:
    metadata:
      labels:
        app: order-service-dev
    spec:
      containers:
        - name: order-service
          image: order-service:dev
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-dev
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084