apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:prod
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-prod
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084